package main.game.common.font;

import java.util.HashMap;

public class BMPFont {
	public static final int[][] NUMBER_0 = new int[][] { { 0xffffff, 0xffffff, 0xffffff }, { 0xffffff, 0, 0xffffff }, { 0xffffff, 0, 0xffffff }, { 0xffffff, 0, 0xffffff }, { 0xffffff, 0xffffff, 0xffffff } };
	public static final int[][] NUMBER_1 = new int[][] { { 0, 0xffffff, 0 }, { 0xffffff, 0xffffff, 0 }, { 0, 0xffffff, 0 }, { 0, 0xffffff, 0 }, { 0, 0xffffff, 0 } };
	public static final int[][] NUMBER_2 = new int[][] { { 0xffffff, 0xffffff, 0xffffff }, { 0, 0, 0xffffff }, { 0xffffff, 0xffffff, 0xffffff }, { 0xffffff, 0, 0 }, { 0xffffff, 0xffffff, 0xffffff } };
	public static final int[][] NUMBER_3 = new int[][] { { 0xffffff, 0xffffff, 0xffffff }, { 0, 0, 0xffffff }, { 0xffffff, 0xffffff, 0xffffff }, { 0, 0, 0xffffff }, { 0xffffff, 0xffffff, 0xffffff } };
	public static final int[][] NUMBER_4 = new int[][] { { 0xffffff, 0, 0xffffff }, { 0xffffff, 0, 0xffffff }, { 0xffffff, 0xffffff, 0xffffff }, { 0, 0, 0xffffff }, { 0, 0, 0xffffff } };
	public static final int[][] NUMBER_5 = new int[][] { { 0xffffff, 0xffffff, 0xffffff }, { 0xffffff, 0, 0 }, { 0xffffff, 0xffffff, 0xffffff }, { 0, 0, 0xffffff }, { 0xffffff, 0xffffff, 0xffffff } };
	public static final int[][] NUMBER_6 = new int[][] { { 0xffffff, 0xffffff, 0xffffff }, { 0xffffff, 0, 0 }, { 0xffffff, 0xffffff, 0xffffff }, { 0xffffff, 0, 0xffffff }, { 0xffffff, 0xffffff, 0xffffff } };
	public static final int[][] NUMBER_7 = new int[][] { { 0xffffff, 0xffffff, 0xffffff }, { 0, 0, 0xffffff }, { 0, 0, 0xffffff }, { 0, 0xffffff, 0 }, { 0, 0xffffff, 0 } };
	public static final int[][] NUMBER_8 = new int[][] { { 0xffffff, 0xffffff, 0xffffff }, { 0xffffff, 0, 0xffffff }, { 0xffffff, 0xffffff, 0xffffff }, { 0xffffff, 0, 0xffffff }, { 0xffffff, 0xffffff, 0xffffff } };
	public static final int[][] NUMBER_9 = new int[][] { { 0xffffff, 0xffffff, 0xffffff }, { 0xffffff, 0, 0xffffff }, { 0xffffff, 0xffffff, 0xffffff }, { 0, 0, 0xffffff }, { 0xffffff, 0xffffff, 0xffffff } };

	public static final int[][][] NUMBERS = new int[][][] { NUMBER_0, NUMBER_1, NUMBER_2, NUMBER_3, NUMBER_4, NUMBER_5, NUMBER_6, NUMBER_7, NUMBER_8, NUMBER_9 };

	public static final int[][] LETTER_A = new int[][] { { 0, 1, 1, 0 }, { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 1, 1, 1, 1 }, { 1, 0, 0, 1 } };
	public static final int[][] LETTER_B = new int[][] { { 1, 1, 1, 0 }, { 1, 0, 0, 1 }, { 1, 1, 1, 0 }, { 1, 0, 0, 1 }, { 1, 1, 1, 0 } };
	public static final int[][] LETTER_C = new int[][] { { 0, 1, 1 }, { 1, 0, 0 }, { 1, 0, 0 }, { 1, 0, 0 }, { 0, 1, 1 } };
	public static final int[][] LETTER_D = new int[][] { { 1, 1, 1, 0 }, { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 1, 1, 1, 0 } };
	public static final int[][] LETTER_E = new int[][] { { 1, 1, 1 }, { 1, 0, 0 }, { 1, 1, 1 }, { 1, 0, 0 }, { 1, 1, 1 } };
	public static final int[][] LETTER_F = new int[][] { { 1, 1, 1 }, { 1, 0, 0 }, { 1, 1, 1 }, { 1, 0, 0 }, { 1, 0, 0 } };
	public static final int[][] LETTER_G = new int[][] { { 0, 1, 1, 1 }, { 1, 0, 0, 0 }, { 1, 0, 1, 1 }, { 1, 0, 0, 1 }, { 0, 1, 1, 1 } };
	public static final int[][] LETTER_H = new int[][] { { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 1, 1, 1, 1 }, { 1, 0, 0, 1 }, { 1, 0, 0, 1 } };
	public static final int[][] LETTER_I = new int[][] { { 1, 1, 1 }, { 0, 1, 0 }, { 0, 1, 0 }, { 0, 1, 0 }, { 1, 1, 1 } };
	public static final int[][] LETTER_J = new int[][] { { 0, 1, 1 }, { 0, 0, 1 }, { 0, 0, 1 }, { 1, 0, 1 }, { 0, 1, 0 } };
	public static final int[][] LETTER_K = new int[][] { { 1, 0, 0, 1 }, { 1, 0, 1, 0 }, { 1, 1, 0, 0 }, { 1, 0, 1, 0 }, { 1, 0, 0, 1 } };
	public static final int[][] LETTER_L = new int[][] { { 1, 0, 0 }, { 1, 0, 0 }, { 1, 0, 0 }, { 1, 0, 0 }, { 1, 1, 1 } };
	public static final int[][] LETTER_M = new int[][] { { 1, 0, 0, 0, 1 }, { 1, 1, 0, 1, 1 }, { 1, 0, 1, 0, 1 }, { 1, 0, 0, 0, 1 }, { 1, 0, 0, 0, 1 } };
	public static final int[][] LETTER_N = new int[][] { { 1, 0, 0, 1 }, { 1, 1, 0, 1 }, { 1, 0, 1, 1 }, { 1, 0, 0, 1 }, { 1, 0, 0, 1 } };
	public static final int[][] LETTER_O = new int[][] { { 0, 1, 1, 0 }, { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 0, 1, 1, 0 } };
	public static final int[][] LETTER_P = new int[][] { { 1, 1, 1, 0 }, { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 1, 1, 1, 0 }, { 1, 0, 0, 0 } };
	public static final int[][] LETTER_Q = new int[][] { { 0, 1, 1, 0 }, { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 0, 1, 1, 0 }, { 0, 0, 0, 1 } };
	public static final int[][] LETTER_R = new int[][] { { 1, 1, 1, 0 }, { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 1, 1, 1, 0 }, { 1, 0, 0, 1 } };
	public static final int[][] LETTER_S = new int[][] { { 0, 1, 1, 1 }, { 1, 0, 0, 0 }, { 0, 1, 1, 0 }, { 0, 0, 0, 1 }, { 1, 1, 1, 0 } };
	public static final int[][] LETTER_T = new int[][] { { 1, 1, 1 }, { 0, 1, 0 }, { 0, 1, 0 }, { 0, 1, 0 }, { 0, 1, 0 } };
	public static final int[][] LETTER_U = new int[][] { { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 0, 1, 1, 0 } };
	public static final int[][] LETTER_V = new int[][] { { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 1, 0, 1, 0 }, { 1, 0, 1, 0 }, { 0, 1, 0, 0 } };
	public static final int[][] LETTER_W = new int[][] { { 1, 0, 0, 0, 1 }, { 1, 0, 1, 0, 1 }, { 1, 0, 1, 0, 1 }, { 1, 0, 1, 0, 1 }, { 0, 1, 0, 1, 0 } };
	public static final int[][] LETTER_X = new int[][] { { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 0, 1, 1, 0 }, { 1, 0, 0, 1 }, { 1, 0, 0, 1 } };
	public static final int[][] LETTER_Y = new int[][] { { 1, 0, 0, 1 }, { 1, 0, 0, 1 }, { 0, 1, 1, 1 }, { 0, 0, 0, 1 }, { 0, 1, 1, 0 } };
	public static final int[][] LETTER_Z = new int[][] { { 1, 1, 1 }, { 0, 0, 1 }, { 0, 1, 0 }, { 1, 0, 0 }, { 1, 1, 1 } };
	public static final int[][] LETTER_PLUS = new int[][] { { 0, 0, 0 }, { 0, 1, 0 }, { 1, 1, 1 }, { 0, 1, 0 } };
	public static final int[][] LETTER_MINUS = new int[][] { { 0, 0, 0 }, { 0, 0, 0 }, { 1, 1, 1 }, { 0, 0, 0 } };
	public static final int[][] LETTER_MULTIPLY = new int[][] { { 0, 0, 0 }, { 1, 0, 1 }, { 0, 1, 0 }, { 1, 0, 1 } };
	public static final int[][] LETTER_EQUAL = new int[][] { { 0, 0, 0 }, { 1, 1, 1 }, { 0, 0, 0 }, { 1, 1, 1 } };
	public static final int[][] LETTER_BRAKET_TO = new int[][] { { 0, 0, 1 }, { 0, 1, 0 }, { 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 } };
	public static final int[][] LETTER_BRAKET_TC = new int[][] { { 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 }, { 0, 1, 0 }, { 1, 0, 0 } };
	public static final int[][] LETTER_BRAKET_BO = new int[][] { { 1, 1 }, { 1, 0 }, { 1, 0 }, { 1, 0 }, { 1, 1 } };
	public static final int[][] LETTER_BRAKET_BC = new int[][] { { 1, 1 }, { 0, 1 }, { 0, 1 }, { 0, 1 }, { 1, 1 } };
	public static final int[][] LETTER_BRAKET_MO = new int[][] { { 0, 1, 1 }, { 0, 1, 0 }, { 1, 0, 0 }, { 0, 1, 0 }, { 0, 1, 1 } };
	public static final int[][] LETTER_BRAKET_MC = new int[][] { { 1, 1, 0 }, { 0, 1, 0 }, { 0, 0, 1 }, { 0, 1, 0 }, { 1, 1, 0 } };
	public static final int[][] LETTER_BRAKET_SO = new int[][] { { 0, 1 }, { 1, 0 }, { 1, 0 }, { 1, 0 }, { 0, 1 } };
	public static final int[][] LETTER_BRAKET_SC = new int[][] { { 1, 0 }, { 0, 1 }, { 0, 1 }, { 0, 1 }, { 1, 0 } };
	public static final int[][] LETTER_QUATION = new int[][] { { 1, 1, 1, 0 }, { 0, 0, 0, 1 }, { 0, 1, 1, 0 }, { 0, 0, 0, 0 }, { 0, 1, 0, 0 } };
	public static final int[][] LETTER_NOTI = new int[][] { { 1 }, { 1 }, { 1 }, { 0 }, { 1 } };
	public static final int[][] LETTER_SPACE = new int[][] { { 0 }, };
	public static final int[][] LETTER_UNDERSCORE = new int[][] { { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 1, 1, 1 } };
	public static final int[][] LETTER_COLON = new int[][] { { 0 }, { 1 }, { 0 }, { 1 } };
	public static final int[][] LETTER_DOT = new int[][] { { 0 }, { 0 }, { 0 }, { 0 }, { 1 } };
	public static final int[][] LETTER_WARNNING = new int[][] { { 0, 0, 1, 1, 0, 0 }, { 0, 1, 0, 0, 1, 0 }, { 1, 0, 1, 0, 0, 1 }, { 1, 0, 0, 1, 0, 1 }, { 0, 1, 0, 0, 1, 0 }, { 0, 0, 1, 1, 0, 0 } };
	public static final int[][] LETTER_SLASH = new int[][] { { 0, 0, 1 }, { 0, 0, 1 }, { 0, 1, 0 }, { 1, 0, 0 }, { 1, 0, 0 }, };

	public static HashMap<Character, int[][]> LETTERS = new HashMap<Character, int[][]>();

	static {
		LETTERS.put('A', LETTER_A);
		LETTERS.put('B', LETTER_B);
		LETTERS.put('C', LETTER_C);
		LETTERS.put('D', LETTER_D);
		LETTERS.put('E', LETTER_E);
		LETTERS.put('F', LETTER_F);
		LETTERS.put('G', LETTER_G);
		LETTERS.put('H', LETTER_H);
		LETTERS.put('I', LETTER_I);
		LETTERS.put('J', LETTER_J);
		LETTERS.put('K', LETTER_K);
		LETTERS.put('L', LETTER_L);
		LETTERS.put('M', LETTER_M);
		LETTERS.put('N', LETTER_N);
		LETTERS.put('O', LETTER_O);
		LETTERS.put('P', LETTER_P);
		LETTERS.put('Q', LETTER_Q);
		LETTERS.put('R', LETTER_R);
		LETTERS.put('S', LETTER_S);
		LETTERS.put('T', LETTER_T);
		LETTERS.put('U', LETTER_U);
		LETTERS.put('V', LETTER_V);
		LETTERS.put('W', LETTER_W);
		LETTERS.put('X', LETTER_X);
		LETTERS.put('Y', LETTER_Y);
		LETTERS.put('Z', LETTER_Z);
		LETTERS.put('+', LETTER_PLUS);
		LETTERS.put('-', LETTER_MINUS);
		LETTERS.put('<', LETTER_BRAKET_TO);
		LETTERS.put('>', LETTER_BRAKET_TC);
		LETTERS.put('(', LETTER_BRAKET_SO);
		LETTERS.put(')', LETTER_BRAKET_SC);
		LETTERS.put('{', LETTER_BRAKET_MO);
		LETTERS.put('}', LETTER_BRAKET_MC);
		LETTERS.put('[', LETTER_BRAKET_BO);
		LETTERS.put(']', LETTER_BRAKET_BC);
		LETTERS.put('=', LETTER_EQUAL);
		LETTERS.put('?', LETTER_QUATION);
		LETTERS.put('!', LETTER_NOTI);
		LETTERS.put('*', LETTER_MULTIPLY);
		LETTERS.put(' ', LETTER_SPACE);
		LETTERS.put('_', LETTER_UNDERSCORE);
		LETTERS.put(':', LETTER_COLON);
		LETTERS.put('.', LETTER_DOT);
		LETTERS.put('/', LETTER_SLASH);
		LETTERS.put('0', NUMBER_0);
		LETTERS.put('1', NUMBER_1);
		LETTERS.put('2', NUMBER_2);
		LETTERS.put('3', NUMBER_3);
		LETTERS.put('4', NUMBER_4);
		LETTERS.put('5', NUMBER_5);
		LETTERS.put('6', NUMBER_6);
		LETTERS.put('7', NUMBER_7);
		LETTERS.put('8', NUMBER_8);
		LETTERS.put('9', NUMBER_9);
	}
}
